export { vernier } from "./plugin";
export type { VernierPluginOptions } from "./plugin";
export { vernier as default } from "./plugin";
export { injectVernierOverlay } from "./core/html";
export { VernierError } from "./core/errors";
export { createVernierOverlayScript } from "./core/overlay-script";
export type { OverlayRuntimeOptions, SessionOutputOptions } from "./core/overlay-options";
export { handleVernierSessionRequest } from "./core/session-handler";
export { resolveFeedbackDirectory, writeSession } from "./core/session-writer";
export { createAgentPrompt, readLatestSessionMarkdown } from "./core/handoff";
export { findLatestIssue, listLatestIssues, markLatestIssue, readLatestSession, updateLatestIssueNote } from "./core/issues";
export type { AgentTemplate, IndexedVernierIssue, IssueStatus } from "./core/issues";
export { resolveSource, sourceResolvers } from "./overlay/source";
export type { SourceLocation, SourceResolution, SourceResolver } from "./overlay/source";
export type { VernierIssue, VernierSession } from "./schema";
export { parseArgs } from "./cli/lib/args";
export type { ParsedArgs } from "./cli/lib/args";
export { debugLog, isDebugEnabled, setDebugEnabled } from "./cli/lib/debug";
